/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FreshProduceRouteImport } from './routes/fresh-produce'
import { Route as FrozenProduceRouteImport } from './routes/frozen-produce'
import { Route as GlobalMarketsRouteImport } from './routes/global-markets'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshProduceRoute = FreshProduceRouteImport.update({
  id: '/fresh-produce',
  path: '/fresh-produce',
  getParentRoute: () => rootRouteImport,
} as any)
const FrozenProduceRoute = FrozenProduceRouteImport.update({
  id: '/frozen-produce',
  path: '/frozen-produce',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalMarketsRoute = GlobalMarketsRouteImport.update({
  id: '/global-markets',
  path: '/global-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/frozen-produce': typeof FrozenProduceRoute
  '/global-markets': typeof GlobalMarketsRoute
  '/quality': typeof QualityRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/frozen-produce': typeof FrozenProduceRoute
  '/global-markets': typeof GlobalMarketsRoute
  '/quality': typeof QualityRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fresh-produce': typeof FreshProduceRoute
  '/frozen-produce': typeof FrozenProduceRoute
  '/global-markets': typeof GlobalMarketsRoute
  '/quality': typeof QualityRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/fresh-produce'
    | '/frozen-produce'
    | '/global-markets'
    | '/quality'
    | '/sustainability'
    | '/products/$slug'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/fresh-produce'
    | '/frozen-produce'
    | '/global-markets'
    | '/quality'
    | '/sustainability'
    | '/products/$slug'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/fresh-produce'
    | '/frozen-produce'
    | '/global-markets'
    | '/quality'
    | '/sustainability'
    | '/products/$slug'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FreshProduceRoute: typeof FreshProduceRoute
  FrozenProduceRoute: typeof FrozenProduceRoute
  GlobalMarketsRoute: typeof GlobalMarketsRoute
  QualityRoute: typeof QualityRoute
  SustainabilityRoute: typeof SustainabilityRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh-produce': {
      id: '/fresh-produce'
      path: '/fresh-produce'
      fullPath: '/fresh-produce'
      preLoaderRoute: typeof FreshProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frozen-produce': {
      id: '/frozen-produce'
      path: '/frozen-produce'
      fullPath: '/frozen-produce'
      preLoaderRoute: typeof FrozenProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-markets': {
      id: '/global-markets'
      path: '/global-markets'
      fullPath: '/global-markets'
      preLoaderRoute: typeof GlobalMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FreshProduceRoute: FreshProduceRoute,
  FrozenProduceRoute: FrozenProduceRoute,
  GlobalMarketsRoute: GlobalMarketsRoute,
  QualityRoute: QualityRoute,
  SustainabilityRoute: SustainabilityRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
